# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '14.1'
  pod 'common', :path => '../common'
end
